#!/bin/bash

## Full installation ##########################
##conda create -n FASTP_env -c bioconda fastp
###############################################

#SBATCH -J fastp
#SBATCH -o ~/stdout/%x.%A_%a.out
#SBATCH -e ~/stderr/%x.%A_%a.err

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@zedat.fu-berlin.de

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=3
#SBATCH --mem=9G
#SBATCH --time=12:00:00

#SBATCH --array=1-4 #####CHANGE VALUE!!!!!

export PATH=~/Software/anaconda3/bin:$PATH
source activate FASTP_env

## Only change this: #######################
FQ_DIR="~/Collomics/pacbio
OUT_DIR="~/Collomics/intermediates/trimmed"
############################################

READ_1=$(ls $FQ_DIR/*R1*.fastq.gz | head -n $SLURM_ARRAY_TASK_ID | tail -n 1)
READ_NAME=$(basename $READ_1 _R1_001.fastq.gz)

fastp --in1 $READ_1 --in2 $FQ_DIR/${READ_NAME}_R2_001.fastq.gz --out1 $OUT_DIR/${READ_NAME}_R1.trimmed.fastq.gz --out2 $OUT_DIR/${READ_NAME}_R2.trimmed.fastq.gz -l 50 -h $OUT_DIR/${READ_NAME}.html -j $OUT_DIR/${READ_NAME}.fastp.json
