#!/bin/bash

## Full installation (hifiasm 0.16.1) ############
##conda create -n HIFIASM_env -c bioconda hifiasm
##################################################

#SBATCH -J hifiasm
#SBATCH -o ~/stdout/%x.%j.out
#SBATCH -e ~/stderr/%x.%j.err

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@zedat.fu-berlin.de

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=64
#SBATCH --mem=240G
#SBATCH --time=5-00:00:00 

export PATH="~/Software/anaconda3/bin:${PATH}"
source activate HIFIASM_env

## Only change this: ############################################
OUT_DIR="~/Collomics/intermediates/hifiasm_l3"
NAME="collomics_BraTor"
HIFI_DIR="~/Collomics/intermediates/trimmed"
#HIC_FQ_1="_R1_001.fastq.gz"
#HIC_FQ_2="_R2_001.fastq.gz"
#################################################################

mkdir -p $OUT_DIR
cd $OUT_DIR
hifiasm -o $NAME -t 64 -l3 --primary --purge-max 63 ${HIFI_DIR}/*.trimmed.fastq.gz 2> ${NAME}.log
#-l0 1 2 3
#awk '/^S/{print ">"$2;print $3}' $NAME\.bp.p_ctg.gfa > $NAME\.c1.fa
#awk '/^S/{print ">"$2;print $3}' $NAME\.bp.a_ctg.gfa > $NAME\.c2.fa
#cd ..
#mv $OUT_DIR/$NAME\.c1.fa .
#mv $OUT_DIR/$NAME\.c2.fa .
