#!/bin/bash

## Using Hifiasm-0.17.4 (r455) beta #############

#SBATCH -J hifiasm
#SBATCH -o ~/stdout/%x.%j.out
#SBATCH -e ~/stderr/%x.%j.err

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@zedat.fu-berlin.de

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=48
#SBATCH --mem=240G
#SBATCH --time=5-00:00:00 

HIFIASM="../Software/hifiasm-r455/hifiasm"

## Only change this: ############################################
OUT_DIR="~/Collomics/intermediates/hifiasm"
NAME="collomics_BraTor"
HIFI_DIR="~/Collomics/intermediates/trimmed"
MAX_DEPTH=$(cat ../genomescope2/k31/Maximum_depth)
#################################################################


mkdir -p ${OUT_DIR}/${NAME}_l0
cd ${OUT_DIR}/${NAME}_l0
$HIFIASM -o ${NAME}_l0 -t 48 -l0 --primary --purge-max $MAX_DEPTH ${HIFI_DIR}/*.trimmed.fastq.gz 2> ${NAME}_l0.log

mkdir -p ${OUT_DIR}/${NAME}_l1
mv ${NAME}_l0.ovlp.source.bin ${OUT_DIR}/${NAME}_l1/${NAME}_l1.ovlp.source.bin
mv ${NAME}_l0.ovlp.reverse.bin ${OUT_DIR}/${NAME}_l1/${NAME}_l1.ovlp.reverse.bin
mv ${NAME}_l0.ec.bin ${OUT_DIR}/${NAME}_l1/${NAME}_l1.ec.bin

cd ${OUT_DIR}/${NAME}_l1
$HIFIASM -o ${NAME}_l1 -t 48 -l1 --primary --purge-max $MAX_DEPTH ${HIFI_DIR}/*.trimmed.fastq.gz 2> ${NAME}_l1.log

mkdir -p ${OUT_DIR}/${NAME}_l2
mv ${NAME}_l1.ovlp.source.bin ${OUT_DIR}/${NAME}_l2/${NAME}_l2.ovlp.source.bin
mv ${NAME}_l1.ovlp.reverse.bin ${OUT_DIR}/${NAME}_l2/${NAME}_l2.ovlp.reverse.bin
mv ${NAME}_l1.ec.bin ${OUT_DIR}/${NAME}_l2/${NAME}_l2.ec.bin

cd ${OUT_DIR}/${NAME}_l2
$HIFIASM -o ${NAME}_l2 -t 48 -l2 --primary --purge-max $MAX_DEPTH ${HIFI_DIR}/*.trimmed.fastq.gz 2> ${NAME}_l2.log

mkdir -p ${OUT_DIR}/${NAME}_l3
mv ${NAME}_l2.ovlp.source.bin ${OUT_DIR}/${NAME}_l3/${NAME}_l3.ovlp.source.bin
mv ${NAME}_l2.ovlp.reverse.bin ${OUT_DIR}/${NAME}_l3/${NAME}_l3.ovlp.reverse.bin
mv ${NAME}_l2.ec.bin ${OUT_DIR}/${NAME}_l3/${NAME}_l3.ec.bin

cd ${OUT_DIR}/${NAME}_l3
$HIFIASM -o ${NAME}_l3 -t 48 -l3 --primary --purge-max $MAX_DEPTH ${HIFI_DIR}/*.trimmed.fastq.gz 2> ${NAME}_l3.log

